package pt.models

import java.time.LocalDateTime

object SamsungHealthModels {

  case class AdvancedGlycationEndproduct(
    create_sh_ver: Int,
    measurement_result: Int,
    percent: Int,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    score: Int,
    deviceuuid: String,
    level_boundary: String,
    pkg_name: String,
    datauuid: String,
    day_time: Long
  )

  case class AdvancedGlycationEndproductRaw(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    binning_data: String,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    version: Option[String],
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class DeviceProfile(
    manufacturer: String,
    providing_step_goal: Option[Int],
    create_sh_ver: Option[String],
    step_source_group: Option[Int],
    device_type: Option[Int],
    backsync_step_goal: Option[Int],
    capability: Option[String],
    modify_sh_ver: Option[Int],
    device_group: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    name: String,
    model: Option[String],
    legacy_deviceuuid: Option[String],
    connectivity_type: Option[String],
    deviceuuid: String,
    pkg_name: String,
    accessory_type: Option[String],
    fixed_name: Option[String],
    datauuid: String
  )

  case class Ecg(
    sample_frequency: Int,
    create_sh_ver: Option[String],
    start_time: LocalDateTime,
    custom: Option[String],
    mean_heart_rate: Double,
    modify_sh_ver: Option[String],
    max_heart_rate: Option[String],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    data_mime: String,
    data: String,
    min_heart_rate: Option[String],
    classification: Option[String],
    sample_count: Int,
    shm_data_id: Option[String],
    time_offset: String,
    shm_device_uuid: Option[String],
    deviceuuid: String,
    comment: Option[String],
    pkg_name: String,
    shm_update_time: Option[String],
    end_time: LocalDateTime,
    chart_data: Option[String],
    datauuid: String,
    shm_create_time: Option[String],
    symptoms: Option[String],
    ecg_version: Option[String]
  )

  case class FloorsClimbed(
    start_time: LocalDateTime,
    custom: Option[String],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    client_data_id: Option[String],
    client_data_ver: Option[String],
    floor: Double,
    raw_data: String,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class Height(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    custom: Option[String],
    height: Double,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String
  )

  case class Hrv(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    custom: Option[String],
    binning_data: String,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    time_offset: String,
    deviceuuid: String,
    comment: Option[String],
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class Movement(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    custom: Option[String],
    binning_data: String,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    time_offset: String,
    deviceuuid: String,
    comment: Option[String],
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class RespiratoryRate(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    custom: Option[String],
    binning_data: String,
    modify_sh_ver: Int,
    average: Double,
    lower_limit: Double,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    client_data_id: Option[String],
    upper_limit: Double,
    client_data_ver: Option[String],
    is_outlier: Int,
    pplib_version: String,
    time_offset: String,
    deviceuuid: String,
    comment: Option[String],
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class SleepStage(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    sleep_id: String,
    custom: Option[String],
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    stage: Int,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class UserProfile(
    text_value: String,
    create_sh_ver: Option[Int],
    float_value: String,
    modify_sh_ver: Option[Int],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    long_value: String,
    key: String,
    blob_value: String,
    int_value: String,
    deviceuuid: String,
    pkg_name: String,
    double_value: String,
    datauuid: String
  )

  case class Weight(
    body_fat_mass: Option[String],
    create_sh_ver: Int,
    start_time: LocalDateTime,
    custom: Option[String],
    height: Option[Double],
    weight: Double,
    muscle_mass: Option[String],
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    client_data_id: Option[String],
    skeletal_muscle: Option[String],
    fat_free_mass: Option[String],
    client_data_ver: Option[String],
    basal_metabolic_rate: Option[String],
    time_offset: String,
    deviceuuid: String,
    skeletal_muscle_mass: Option[String],
    comment: Option[String],
    fat_free: Option[String],
    pkg_name: String,
    body_fat: Option[String],
    datauuid: String,
    vfa_level: Option[String],
    total_body_water: Option[String]
  )

  case class ActivityDaySummary(
    movement_type: Int,
    create_sh_ver: Int,
    energy_type: Int,
    exercise_time: Int,
    step_count: Int,
    exercise_calorie_target: Int,
    active_time: Int,
    target: Int,
    others_time: Int,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    floors_target: Int,
    create_time: LocalDateTime,
    floor_count: Double,
    dynamic_active_time_target: Int,
    exercise_time_target: Int,
    goal: Int,
    longest_active_time: Int,
    score: Int,
    move_hourly_count: Int,
    duration_type: Int,
    move_hourly_target: Int,
    distance: Double,
    dynamic_active_time: Int,
    calorie: Double,
    extra_data: String,
    deviceuuid: String,
    run_time: Int,
    pkg_name: String,
    walk_time: Int,
    longest_idle_time: Int,
    datauuid: String,
    day_time: LocalDateTime
  )

  case class ActivityGoal(
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    value: Int,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    set_time: Long,
    datauuid: String
  )

  case class ActivityLevel(
    activity_level: Int,
    start_time: LocalDateTime,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String
  )

  case class Badge(
    number_of_streak: Option[Int],
    start_time: LocalDateTime,
    exercise_type: Option[Int],
    device_type: Option[String],
    status: Int,
    sleep_coaching_session_uuid: Option[String],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    source_pkg_name: Option[String],
    key: String,
    program_id: Option[String],
    is_shown: Option[Int],
    time_offset: String,
    extra_data: Option[String],
    deviceuuid: String,
    pkg_name: String,
    exercise_data_uuid: Option[String],
    controller_id: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class BestRecords(
    source_id: String,
    device_type: Option[Int],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    source_pkg_name: Option[String],
    date: Long,
    `type`: Int,
    value: Double,
    is_shown: Option[Int],
    extra_data: Option[String],
    extra_type: Option[Int],
    deviceuuid: String,
    pkg_name: String,
    controller_id: String,
    datauuid: String
  )

  case class CaloriesBurnedDetails(
    active_calories_goal: Option[String],
    version: Option[String],
    extra_data: String,
    exercise_calories: Option[String],
    total_exercise_calories: Double,
    create_sh_ver: Int,
    tef_calorie: Double,
    active_time: Int,
    rest_calorie: Double,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    active_calorie: Double,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String,
    day_time: Long
  )

  case class Exercise(
    live_data_internal: String,
    mission_value: Option[Int],
    race_target: Option[Int],
    subset_data: Option[String],
    start_longitude: Option[Double],
    routine_datauuid: Option[String],
    total_calorie: Option[Double],
    completion_status: Option[Int],
    pace_info_id: Option[String],
    activity_type: Option[String],
    pace_live_data: Option[String],
    sensing_status: Option[String],
    source_type: Option[Int],
    mission_type: Option[Int],
    ftp: Option[String],
    tracking_status: Option[Int],
    program_id: Option[String],
    title: Option[String],
    reward_status: Option[Int],
    heart_rate_sample_count: Option[String],
    start_latitude: Option[Double],
    mission_extra_value: Option[Double],
    program_schedule_id: Option[String],
    heart_rate_deviceuuid: Option[String],
    location_data_internal: Option[String],
    custom_id: Option[String],
    additional_internal: Option[String],
    duration: Option[Int],
    additional: Option[String],
    create_sh_ver: Option[Int],
    mean_caloricburn_rate: Option[String],
    location_data: Option[String],
    start_time: LocalDateTime,
    exercise_type: Option[Int],
    custom: Option[String],
    max_altitude: Option[Double],
    incline_distance: Option[Double],
    mean_heart_rate: Option[Double],
    count_type: Option[Int],
    mean_rpm: Option[String],
    min_altitude: Option[Double],
    modify_sh_ver: Option[Int],
    max_heart_rate: Option[Double],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    client_data_id: Option[String],
    max_power: Option[String],
    max_speed: Option[Double],
    mean_cadence: Option[Double],
    min_heart_rate: Option[Double],
    client_data_ver: Option[String],
    count: Option[Int],
    distance: Option[Double],
    max_caloricburn_rate: Option[String],
    calorie: Option[Double],
    max_cadence: Option[Double],
    decline_distance: Option[Double],
    vo2_max: Option[Double],
    time_offset: String,
    deviceuuid: String,
    max_rpm: Option[String],
    comment: Option[String],
    live_data: String,
    mean_power: Option[String],
    mean_speed: Option[Double],
    pkg_name: String,
    altitude_gain: Option[Double],
    altitude_loss: Option[String],
    exercise_custom_type: Option[String],
    auxiliary_devices: Option[String],
    end_time: LocalDateTime,
    datauuid: String,
    sweat_loss: Option[Int]
  )

  case class ExerciseCustomExercise(
    custom_name: String,
    custom_type: Int,
    preference: String,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    deviceuuid: String,
    pkg_name: String,
    custom_id: String,
    datauuid: String,
    visibility: Int
  )

  case class ExerciseHrZone(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    max_hr_custom: Option[String],
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    at: Int,
    ant: Int,
    version: Int,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    max_hr_auto: Int,
    datauuid: String
  )

  case class ExerciseMaxHeartRate(
    at_heart_rate: Int,
    start_time: LocalDateTime,
    max_heart_rate: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    time_offset: String,
    deviceuuid: String,
    ant_heart_rate: Int,
    pkg_name: String,
    datauuid: String
  )

  case class ExercisePacesetter(
    duration: Int,
    description: String,
    deprecated: Int,
    custom: Option[String],
    gender: String,
    activity_type: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    pace_element: String,
    name: String,
    grade: Int,
    level: Int,
    pace_goal_type: Int,
    distance: Double,
    deviceuuid: String,
    pkg_name: String,
    pace_type: Int,
    datauuid: String,
    info_id: Int
  )

  case class ExercisePeriodizationTrainingProgram(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    program: String,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String
  )

  case class ExercisePeriodizationTrainingSchedule(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    coach_id: String,
    status: Int,
    schedule: String,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    `type`: Int,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    program_uuid: String,
    datauuid: String
  )

  case class ExerciseRecoveryHeartRate(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    time_offset: String,
    deviceuuid: String,
    exercise_id: String,
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String,
    heart_rate: String
  )

  case class ExerciseRoute(
    duration: Int,
    exercise_type: Int,
    start_longitude: Double,
    author: Option[String],
    custom: Option[String],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    source_data: String,
    source_type: Int,
    name: Long,
    route_id: Option[String],
    level: Option[String],
    distance: Double,
    end_latitude: Double,
    start_latitude: Double,
    deviceuuid: String,
    end_longitude: Double,
    mean_grade: Double,
    pkg_name: String,
    altitude_gain: Double,
    datauuid: String
  )

  case class ExerciseWeather(
    uv_index: Option[String],
    sunset_time: Option[String],
    start_time: LocalDateTime,
    latitude: Double,
    custom: Option[String],
    wind_direction: String,
    phrase: String,
    sundown_time: Option[String],
    temperature_scale: Int,
    content_provider: String,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    `type`: Int,
    longitude: Double,
    temperature: Double,
    humidity: Int,
    time_offset: String,
    deviceuuid: String,
    exercise_id: String,
    pkg_name: String,
    wind_speed_unit: String,
    forecast_time: Option[String],
    wind_speed: Double,
    icon_info_id: Int,
    datauuid: String
  )

  case class GoalHistory(
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    `type`: Int,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    set_time: Long,
    controller_id: String,
    datauuid: String
  )

  case class HspReferences(
    hsp_id: String,
    shealth_id: String,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    shealth_data_type: Int,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String
  )

  case class InsightMessage(
    is_ai_generated: Int,
    feedback_type: Int,
    service_id: String,
    description: String,
    exposure_uri: String,
    condition_id: String,
    msg_id: String,
    update_time: String,
    create_time: String,
    is_viewed: String,
    tag: String,
    category: String,
    title: String,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String,
    day_time: String
  )

  case class Preferences(
    text_value: Option[String],
    service_id: Option[String],
    float_value: Option[String],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    long_value: Option[Long],
    tag: Option[String],
    blob_value: Option[String],
    int_value: Option[Int],
    deviceuuid: String,
    pkg_name: String,
    double_value: Option[String],
    datauuid: String
  )

  case class Report(
    timezone: String,
    start_date: Long,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    `type`: Int,
    is_empty: Int,
    version: Int,
    deviceuuid: String,
    content: String,
    pkg_name: String,
    datauuid: String,
    compressed_content: String
  )

  case class Rewards(
    number_of_streak: Option[String],
    start_time: Option[LocalDateTime],
    exercise_type: Option[String],
    device_type: Option[String],
    exercise_session_id: Option[String],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    source_pkg_name: Option[String],
    program_id: Option[String],
    title: String,
    time_offset: Option[String],
    extra_data: Option[Int],
    deviceuuid: String,
    pkg_name: String,
    controller_id: String,
    end_time: LocalDateTime,
    datauuid: String,
    is_visible: Int
  )

  case class ServicePreferences(
    text_value: Option[String],
    service_id: Option[String],
    float_value: Option[String],
    update_time: String,
    create_time: String,
    long_value: Option[String],
    key: String,
    tag: Option[String],
    blob_value: Option[String],
    int_value: Option[String],
    deviceuuid: String,
    pkg_name: String,
    double_value: Option[String],
    datauuid: Option[String]
  )

  case class ShmDevice(
    create_sh_ver: Int,
    device_name: String,
    device_type: Long,
    capability: String,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    shm_data_id: String,
    time_offset: String,
    shm_device_uuid: String,
    deviceuuid: String,
    comment: Option[String],
    pkg_name: String,
    fixed_name: String,
    shm_update_time: LocalDateTime,
    datauuid: String,
    shm_create_time: LocalDateTime
  )

  case class Sleep(
    total_sleep_time_weight: Option[String],
    original_efficiency: Option[String],
    mental_recovery: Option[Double],
    wake_score: Option[String],
    factor_01: Option[Int],
    factor_02: Option[Int],
    factor_03: Option[Int],
    factor_04: Option[Int],
    factor_05: Option[Int],
    factor_06: Option[Int],
    factor_07: Option[Int],
    factor_08: Option[Int],
    factor_09: Option[Int],
    factor_10: Option[String],
    deep_score: Option[String],
    integrated_id: Option[String],
    latency_weight: Option[String],
    has_sleep_data: Option[Int],
    bedtime_detection_delay: Option[Int],
    sleep_efficiency_with_latency: Option[String],
    wakeup_time_detection_delay: Option[Int],
    total_rem_duration: Option[Int],
    combined_id: Option[String],
    nap_score: Option[String],
    sleep_type: Option[Int],
    sleep_latency: Option[Int],
    data_version: Option[Int],
    latency_score: Option[String],
    deep_weight: Option[String],
    rem_weight: Option[String],
    physical_recovery: Option[Double],
    original_wake_up_time: Option[LocalDateTime],
    movement_awakening: Option[Double],
    is_integrated: Option[String],
    original_bed_time: Option[LocalDateTime],
    goal_bed_time: Option[Int],
    quality: Option[Int],
    extra_data: Option[String],
    wake_weight: Option[String],
    rem_score: Option[String],
    goal_wake_up_time: Option[Int],
    sleep_cycle: Option[Int],
    total_light_duration: Option[Int],
    efficiency: Option[Double],
    sleep_score: Option[Int],
    sleep_duration: Option[Int],
    stage_analyzed_type: Option[Int],
    total_sleep_time_score: Option[String],
    create_sh_ver: Option[Int],
    start_time: LocalDateTime,
    custom: Option[String],
    modify_sh_ver: Option[Int],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    client_data_id: Option[String],
    client_data_ver: Option[String],
    time_offset: String,
    deviceuuid: String,
    comment: Option[String],
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class SleepCombined(
    total_sleep_time_weight: Option[String],
    original_efficiency: Option[String],
    create_sh_ver: Int,
    start_time: LocalDateTime,
    mental_recovery: Double,
    wake_score: Option[String],
    factor_01: Int,
    factor_02: Int,
    factor_03: Int,
    factor_04: Int,
    factor_05: Int,
    factor_06: Int,
    factor_07: Int,
    factor_08: Int,
    factor_09: Int,
    factor_10: Option[String],
    deep_score: Option[String],
    latency_weight: Option[String],
    has_sleep_data: Int,
    sleep_efficiency_with_latency: Option[String],
    total_rem_duration: Int,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    nap_score: Option[String],
    create_time: LocalDateTime,
    client_data_id: Option[String],
    sleep_type: Option[String],
    data_version: Int,
    latency_score: Option[String],
    deep_weight: Option[String],
    rem_weight: Option[String],
    physical_recovery: Double,
    original_wake_up_time: Option[String],
    client_data_ver: Option[String],
    movement_awakening: Double,
    original_bed_time: Option[String],
    goal_bed_time: Int,
    quality: Option[String],
    time_offset: String,
    extra_data: Option[String],
    wake_weight: Option[String],
    deviceuuid: String,
    rem_score: Option[String],
    goal_wake_up_time: Int,
    sleep_cycle: Int,
    total_light_duration: Int,
    efficiency: Double,
    sleep_score: Int,
    pkg_name: String,
    sleep_duration: Int,
    stage_analyzed_type: Int,
    end_time: LocalDateTime,
    datauuid: String,
    stage_analysis_type: Option[String],
    total_sleep_time_score: Option[String]
  )

  case class SleepRawData(
    create_sh_ver: Int,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    sleep_uuid: String,
    data: String,
    version: Int,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String
  )

  case class SocialServiceStatus(
    status: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    service_type: Int,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String
  )

  case class StepDailyTrend(
    binning_data: String,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    source_pkg_name: String,
    source_type: Int,
    count: Int,
    speed: Double,
    distance: Double,
    calorie: Double,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String,
    day_time: Long
  )

  case class TrackerFloorsDaySummary(
    create_sh_ver: Int,
    binning_data: String,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    floor_count: Int,
    version_code: Int,
    deviceuuid: String,
    pkg_name: String,
    datauuid: String,
    day_time: Long
  )

  case class TrackerHeartRate(
    source: Option[String],
    tag_id: Int,
    create_sh_ver: Int,
    heart_beat_count: Int,
    start_time: LocalDateTime,
    custom: Option[String],
    binning_data: Option[String],
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    client_data_id: Option[String],
    max: Option[String],
    min: Option[String],
    client_data_ver: Option[String],
    time_offset: String,
    deviceuuid: String,
    comment: Option[String],
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String,
    heart_rate: Double
  )

  case class TrackerPedometerDaySummary(
    create_sh_ver: Int,
    step_count: Int,
    binning_data: String,
    active_time: Int,
    recommendation: Int,
    modify_sh_ver: Int,
    run_step_count: Int,
    update_time: LocalDateTime,
    source_package_name: String,
    create_time: LocalDateTime,
    source_info: Option[String],
    speed: Double,
    distance: Double,
    calorie: Double,
    walk_step_count: Int,
    deviceuuid: String,
    pkg_name: String,
    healthy_step: Int,
    achievement: String,
    datauuid: String,
    day_time: Long
  )

  case class TrackerPedometerStepCount(
    duration: Int,
    version_code: Int,
    run_step: Int,
    walk_step: Int,
    start_time: LocalDateTime,
    sample_position_type: Option[String],
    custom: Option[String],
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    count: Int,
    speed: Double,
    distance: Double,
    calorie: Double,
    time_offset: String,
    deviceuuid: String,
    pkg_name: String,
    end_time: LocalDateTime,
    datauuid: String
  )

  case class VitalityNapData(
    create_sh_ver: Int,
    start_time: LocalDateTime,
    modify_sh_ver: Int,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    time_offset: String,
    vitality_day_time: Long,
    deviceuuid: String,
    pkg_name: String,
    score_before: Double,
    end_time: LocalDateTime,
    datauuid: String,
    score_after: Double
  )

  case class VitalityScore(
    activity_level: Int,
    activity_score: Double,
    create_sh_ver: Int,
    active_time_scale: Double,
    activity_balance_short_term_activity: Option[String],
    activity_balance_long_term_activity: Option[String],
    shr_balance_scale: Double,
    mvpa_time_optimal_range_max: Option[String],
    mvpa_time_optimal_range_min: Option[String],
    max_hr: Double,
    active_time: Int,
    shrv_balance_scale: Double,
    main_sleep_wake_up_time: Long,
    mvpa_impulse_optimal_range_max: Option[String],
    mvpa_impulse_optimal_range_min: Option[String],
    shr_baseline_max: Double,
    shr_baseline_min: Double,
    shr_calculation_index: Int,
    mvpa_time: Int,
    modify_sh_ver: Int,
    sleep_balance: Double,
    update_time: LocalDateTime,
    create_time: LocalDateTime,
    total_score: Double,
    data_version: Int,
    avg_mid_sleep_time: Double,
    mvpa_time_range_max: Option[String],
    mvpa_time_range_min: Option[String],
    mvpa_impulse: Double,
    shrv_calculation_index: Int,
    sleep_regularity_scale: Double,
    stable_hr_time_rate: Double,
    active_time_optimal_range_max: Option[String],
    active_time_optimal_range_min: Option[String],
    sleep_timing: Double,
    shr_score: Double,
    shr_value: Double,
    mvpa_impulse_scale: Double,
    sleep_regularity: Double,
    sleep_timing_scale: Double,
    prev_shrv_avg: Double,
    mvpa_time_scale: Double,
    deviceuuid: String,
    sleep_score: Double,
    sleep_duration_scale: Double,
    activity_balance: Option[String],
    activity_balance_range_max: Option[String],
    activity_balance_range_min: Option[String],
    mvpa_impulse_range_max: Option[String],
    mvpa_impulse_range_min: Option[String],
    pkg_name: String,
    sleep_balance_scale: Double,
    shrv_score: Double,
    shrv_value: Double,
    sleep_duration: Int,
    activity_balance_scale: Option[String],
    active_time_range_max: Option[String],
    active_time_range_min: Option[String],
    shrv_baseline_max: Double,
    shrv_baseline_min: Double,
    datauuid: String,
    prev_shr_avg: Double,
    day_time: LocalDateTime,
    shrv_penalty: Int,
    activity_balance_optimal_range_max: Option[String],
    activity_balance_optimal_range_min: Option[String]
  )
}
